### ISSUE TITLE
Update bevy-inspector-egui to remove bevy 0.8 dependencies

### ISSUE THREAD

**Issue by laundmo** [jkb0o/belly#26]
The version of bevy-inspector-egui this relies on depends on bevy 0.8, causing duplicate compilation of many crates

```
├── belly v0.1.0 (https://github.com/jkb0o/belly?branch=main#9c5b154e)
│   ├── belly_core v0.1.0 (https://github.com/jkb0o/belly?branch=main#9c5b154e)
│   │   ├── bevy v0.9.1 (https://github.com/laundmo/bevy?branch=bevy_0.9_overlay#0ff16963)
│   │   │   └── bevy_internal v0.9.1 (https://github.com/laundmo/bevy?branch=bevy_0.9_overlay#0ff16963)
│   │   ├── bevy-inspector-egui v0.13.0
│   │   │   ├── bevy v0.8.1
```
https://github.com/jkb0o/belly/blob/9c5b154eabb29fd99b3f03e9e40c2568bd97ad20/crates/belly_core/Cargo.toml#L10

**Comment by laundmo** [comment]
oh wow, seems like the dependency was unused? glad i caight that then

**Comment by jkb0o** [comment]
@laundmo at this stage of development it is possible to have more bugs like this. I'll investigate & cleanup deps before release. Thanks a lot!
