### ISSUE TITLE
Is it possible to passe a custume bevy image

### ISSUE THREAD

**Issue by bekraoui** [jkb0o/belly#35]
Hi, thank you for the hard work, this library is exactly what i was looking for.

I'm rendering moving objects to a texture and i want to display the my render inside the user interface.

Is it possible to passe a custume bevy image to the img component in stead of a file?

**Comment by jkb0o** [comment]
Not now, but it looks pretty easy to implement. Will do it shortly.

**Comment by bekraoui** [comment]
Thank you for your responsiveness 👍👍👍

**Comment by jkb0o** [comment]
@bekraoui it is now possible to pass the handle to `<img src>` as well as path to asset:
```rust
let img0 = "icon.png";
let img1: Handle<Image> = asset_server.load("bevy_logo_light.png");
let img2: Handle<Image> = asset_server.load("bevy_logo_dark.png");
commands.add(eml! {
    <body>
        <img src=img0/><br/>
        <img src=img1/><br/>
        <img src=img2/><br/>
    </body>
});
```
There is example: https://github.com/jkb0o/belly/blob/main/examples/image-sources.rs
