### ISSUE TITLE
img sometimes not present, style.display is None

### ISSUE THREAD

**Issue by gavxin** [jkb0o/belly#37]
Hi, first thank you for your great work!

When I play with the `img` widget, sometimes the image and it's content not presented, using inspector egui, I fount that the `style.display` is `Display::None`, but image already complete load.

https://github.com/jkb0o/belly/blob/bf05d3b36136ac370ed099b3100d724b563a6c9a/crates/belly_widgets/src/img.rs#L24-L25
```rust
        app.add_system(load_img);
        app.add_system(update_img_size.after(load_img));
```
I try to order these systems, and it fixed the issue, but I'm not sure it should ordered or not.

**Comment by jkb0o** [comment]
That makes scenes! Thank you! There was also possible problem when image doesn't changes, but ordering systems looks good anyway.
