### ISSUE TITLE
Impl `<panel>` widget

### ISSUE THREAD

**Issue by jkb0o** [jkb0o/belly#44]
Current visible widgets use node-inside-node to achieve bordered panel look (button, ranges, text input).
The layout & styling will be easier to understand with `panel`: bordered box.

Existed widgets should use this panel where possible.

**Comment by ethereumdegen** [comment]
I agree. It could use code from nickcomua 's Follow widget (perhaps?) and show have a way to be 'hidden' or 'shown'.   This is very common in game guis such as for an 'inventory' panel.

**Comment by jkb0o** [comment]
This will be done right in `polako` (#77)
