### ISSUE TITLE
quick OOM after adding some simple eml

### ISSUE THREAD

**Issue by Dolphin2Point1** [jkb0o/belly#52]
After adding some eml to my program, the program starts allocating memory like crazy. I've been able to reproduce the problem when you attach eml, which has a base component with (a) child eml component(s) (like a div or a label), to an entity, like as shown below.
```rust
let entity = commands.spawn_empty().id();

commands.add(eml! {
    <div {entity}>
        <div>"this is a test!"</div>
    </div>
});
```
I'm using linux, but I've also replicated the problem on another windows machine.
If you do not attach it to an entity or do not add a child component, the runaway memory allocation does not occur.
With heaptrack, I've diagnosed this issue to be when adding to an ElementsBranch in [belly_core::ess::property::Property::apply_defaults](https://github.com/jkb0o/belly/blob/main/crates/belly_core/src/ess/property/mod.rs#L307). (presumably after line 307) 
[Here is a zip containing the heaptrack file](https://github.com/jkb0o/belly/files/10952609/heaptrack.zip) (which heaptrack already compressed into a zst, but github does not support zsts)

**Comment by jkb0o** [comment]
Cool! Thank you!

Looks like I do not carefully handle cases where you define the root entity of your `eml`.
I'll dive into it, but it may take some time.

Current workaround is to provide a root entity by a custom `render_to` call instead of defining it inside the eml:

```rust
    let entity = commands.spawn_empty().id();
    commands.add(eml! {
        <div>
            <div>"this is a test!"</div>
        </div>
    }.render_to(entity));
```

**Comment by jkb0o** [comment]
This should work now with upstream (don't forget to `cargo update`).

I'm not sure about your usecase, but providing top-level entity is not a good idea in general. If you want to add some eml-based content as the child to another entity, it is better to use `Elements` system param:
```rust
fn handle_death_system(
    mut elements: Elements
) {
    // add child to element with id `popups`
    elements.select("#popups").add_child(eml! {
        <span>Hello world!</span>
    });
    // add child to custom entity
    elements.entity(my_entity).add_child(eml! {
        <span>Hello world!</span>
    });
}
```

There is a section in the README: https://github.com/jkb0o/belly#modifying

**Comment by Dolphin2Point1** [comment]
I see, thanks for the quick response.
