### ISSUE TITLE
DIV doesn't create a new line

### ISSUE THREAD

**Issue by mlp1802** [jkb0o/belly#55]
This is the for-loop example..
![Screenshot from 2023-04-05 19-19-04](https://user-images.githubusercontent.com/4717892/230155988-17164393-94c9-4005-9429-171562e3d97f.png)

**Comment by mlp1802** [comment]
Main branch, bevy 0.11

**Comment by mlp1802** [comment]
SOLVED: need to use  flex-direction:column;

**Comment by jkb0o** [comment]
Well, the div is unfortunately broken. Concept of the div makes the sense if there is inline/block modes supported and there is some element that can layout children in rich-text-like.  For now the div behaves exactly like the span. You can use `<br/>`/`<brl/>` inside `flex-wrap: wrap` elements to add line brakes manually for now.

**Comment by mlp1802** [comment]
What I did was put the line breaking divs inside another div with the property flex-direction:column
