### ISSUE TITLE
[Suggest] commit a GitHub project

### ISSUE THREAD

**Issue by ryuujo1573** [jkb0o/belly#60]
Hi, an amateur Web developer here and I'm willing to help on implementing features if possible :)

I was wondering **what about to create a GitHub project** and write down our needs and future to-dos?
Doing so make us able to track things up and keep organized whenever we're back on this!

> By the way I can help on documentations and implementations (hopefully I won't f**k up with the codes)

> Though I'm totally a noob of rust-lang, and there's a long way ahead to learn along with 🤔 ...
Butt it's fun 😀 and for me, might be the first repository of long-term contributions.

Looking for your reply

**Comment by jkb0o** [comment]
Thank you so much for your suggestion. I believe this is a good Idea. And I will do this with the `polako` when MVP will be ready (#77)
