### ISSUE TITLE
drain_filter not found error in connect.rs

### ISSUE THREAD

**Issue by ccleavinger** [jkb0o/belly#79]
I was following Phaestus Fox's bevy 2d platformer tutorial and git cloned his repo when I tried to run it I got this error:

error[E0599]: no method named `drain_filter` found for struct `std::collections::HashMap` in the current scope
   --> C:\Users\caleb\.cargo\git\checkouts\belly-6f46a1ea7d2f8371\2157ac7\crates\belly_core\src\relations\connect.rs:314:33
    |
314 |             connections.sources.drain_filter(|entity, _| {
    |             --------------------^^^^^^^^^^^^ method not found in `HashMap<Option<Entity>, Vec<(Option<Entity>, Handler<Q, E>)>>`

I've seen people mention that this is a nightly feature and I've built with my rust-toolchain.toml set to nightly and stable, both times I've gotten this exact same error.

**Comment by jkb0o** [comment]
Looks like the `belly` version should be specified. The platformer repo uses own belly fork: https://github.com/PhaestusFox/bevy_platformer/blob/be3859de4a6c12fd712dfd13fb7946333b251c03/Cargo.toml#L22C1-L22C57

It probably will compile if you use original repo and specify exact revesion, something like:
```toml
belly = {git="https://github.com/jkb0o/belly.git" rev="ddd29fc" }
```

**Comment by ccleavinger** [comment]
Ok thanks! Sorry for the issue, still new to rust.
